### ISSUE TITLE
does not even work

### ISSUE THREAD

**Issue by Unixware** [fdufnews/SMART_Response_BASIC#2]
starts uploading then "avrdude: verification error; content mismatch" and the device is bricked!

**Comment by fdufnews** [comment]
What hardware changes have you made to the Terminal?
How did you do the download?

**Comment by Unixware** [comment]
thanks for the help

just the external SD set to 0  (on host.c) as I don't use an external SD (the mod) yet.
Download (upload in fact) via USBasp ,  (Tools -> Burn bootloader) , but I m not sure about the 'board' settings, there is one "Smartresponse XE Optiboot" that I used.

**Comment by Unixware** [comment]
works.. but the procedure - in my case- was : 
* compile the ino on Arduino IDE 
* burn to Smart XE via :

**avrdude -P USB -c usbasp -p m128rfa1 -B 5 -U flash:w:SMART_Response_BASIC.ino.with_bootloader.hex:i**

**Comment by fdufnews** [comment]
>avrdude -P USB -c usbasp -p m128rfa1 -B 5 -U flash:w:SMART_Response_BASIC.ino.with_bootloader.hex:i

This line is necessary if you use an USBASP connected to the SPI bus.

If you want to use "Smart response XE Optiboot" you should first have access to the serial port of the processor. I am afraid I didn't say anything about it on the repo.

**Comment by Unixware** [comment]
I could not find much info on that on web, even other people did not explain it on similar projects.
I had the impression would be something straight away using the SPI bus and Arduino IDE, at least if you can update it for
future reference, I know those devices are not very common to find, but in anycase, thanks.

**Comment by fdufnews** [comment]
[Here are the steps to prepare the terminal](https://github.com/fdufnews/srxe_cc1101/blob/master/README.md#preparing-the-srxe)
<s>I need to add the link to the readme. Maybe I'd better ask if I can duplicate this part on my readme in case the other repo disappear.</s> I just changed my mind and made a fork of the repo so the link will last as long as my repo will do.

That said, using the SPI as the advantage that you don't need to open the terminal and make hardware modification as the SPI signals are accessible through the case in the battery housing.
